import { defaultFeatures } from '../db/settingsSchema.js';

// The feature inventory. releases.json names its features from these ids,
// so an id is never renamed. Not imported by the app bundle.
//
// Rule: an optional feature ships behind a Features toggle in the relevant Settings category, with
// flag set to its settings.features key and default matching
// defaultFeatures. A behavior controlled by another setting names that
// setting in flag as prose (biometrics, daily reboot, RAW archive retention),
// as does one gated by hardware (base control). Always-on work carries
// flag: null and says why in rationale.
type ManifestEntry = {
  id: string;
  title: string;
  description: string;
  category: 'platform' | 'safety' | 'ui' | 'biometrics';
  version: string; // the version whose work finalized this entry's current state
  flag: keyof typeof defaultFeatures | null | string;
  default: boolean | 'n/a';
  touchpoints: string[];
  depends_on: string[];
  reversible: boolean;
  tests: string[];
  upstream_offer: boolean;
  rationale: string;
};

export const FEATURES_MANIFEST: ManifestEntry[] = [
  {
    id: 'cooling-warning', title: 'Cooling warning',
    description: 'Warns when measured water keeps warming during sustained cooling demand. Does not send device commands.',
    category: 'safety', version: '3.7.0', flag: 'coolingWarning', default: false,
    touchpoints: ['biometrics/firmware_telemetry.py', 'server/src/firmware/coolingWarning.ts', 'app/src/components/CoolingNotice.tsx'],
    depends_on: ['biometrics'], reversible: true,
    tests: ['server/src/firmware/coolingWarning.test.ts', 'app/src/components/CoolingNotice.test.tsx'],
    upstream_offer: true,
    rationale: 'An optional observation. Threshold ideas from podd were reimplemented independently.',
  },
  {
    id: 'tap-diagnostics', title: 'Tap diagnostics',
    description: 'Records button and tap candidates on System status, with a JSON export. Does not dispatch actions.',
    category: 'ui', version: '3.7.0', flag: 'tapDiagnostics', default: false,
    touchpoints: ['biometrics/firmware_taps.py', 'server/src/firmware', 'app/src/pages/StatusPage/TapDiagnostics.tsx'],
    depends_on: ['biometrics'], reversible: true,
    tests: ['biometrics/__tests__/test_firmware_taps.py', 'server/src/firmware/firmwareTelemetry.test.ts'],
    upstream_offer: true, rationale: 'Diagnostic candidates need labelled captures before they can drive bed actions.',
  },
  {
    id: 'firmware-health', title: 'Firmware health',
    description: 'Shows selected firmware health messages and new sensor-loss counters on System status. Needs Biometrics.',
    category: 'biometrics', version: '3.7.0', flag: 'firmwareHealth', default: false,
    touchpoints: ['biometrics/firmware_health.py', 'server/src/firmware/healthFeed.ts', 'app/src/pages/StatusPage/FirmwarePanel.tsx'],
    depends_on: ['biometrics'], reversible: true,
    tests: ['biometrics/__tests__/test_firmware_health.py', 'server/src/firmware/firmwareTelemetry.test.ts'],
    upstream_offer: true, rationale: 'Optional diagnostics. Log severity alone is not evidence of a fault.',
  },
  {
    id: 'firmware-target-readout', title: 'Firmware target',
    description: 'Shows the thermostat target reported by firmware, separately from the legacy temperature controls.',
    category: 'ui', version: '3.7.0', flag: 'firmwareTargetReadout', default: false,
    touchpoints: ['biometrics/firmware_telemetry.py', 'server/src/firmware', 'app/src/pages/StatusPage/FirmwarePanel.tsx'],
    depends_on: ['biometrics'], reversible: true,
    tests: ['server/src/firmware/firmwareTelemetry.test.ts', 'app/src/pages/StatusPage/FirmwarePanel.test.tsx'],
    upstream_offer: true, rationale: 'Optional readout. Stored temperatures and outgoing commands keep their existing convention.',
  },
  {
    id: 'metrics-retention',
    title: 'Metrics retention',
    description: 'Opt-in, off by default. Deletes only detailed vitals older than 30 days. '
      + 'Never deletes nightly summaries, sleep records, scores or movement. Deleted detail cannot be restored.',
    category: 'biometrics',
    version: '3.7.0',
    flag: 'metricsRetention',
    default: false,
    touchpoints: [
      'server/src/jobs/metricsRetention.ts', 'server/src/jobs/runMetricsRetention.ts',
      'server/src/jobs/primeScheduler.ts', 'app/src/pages/SettingsPage/FeaturesSection/FeaturesSection.tsx',
      'app/src/pages/SettingsPage/SettingsPage.tsx',
    ],
    depends_on: [],
    reversible: false,
    tests: ['server/src/jobs/metricsRetention.test.ts', 'server/src/jobs/runMetricsRetention.test.ts',
      'app/src/pages/SettingsPage/FeaturesSection/FeaturesSection.test.tsx',
      'app/src/pages/SettingsPage/SettingsPage.categories.test.tsx'],
    upstream_offer: true,
    rationale: 'Age-based pruning requires opt-in. Freed pages can be reused; the database file does not shrink.',
  },
  {
    id: 'metrics-low-disk-protection',
    title: 'Low-disk protection',
    description: 'On by default. Below 150 MiB free, deletes the oldest detailed vitals in bounded batches '
      + 'until 16 MiB of SQLite pages are reusable. Keeps at least the last two nights of detail. '
      + 'Never deletes nightly summaries, sleep records, scores or movement. '
      + 'Stops growth by reusing space; does not shrink the database file or run VACUUM.',
    category: 'biometrics',
    version: '3.7.0',
    flag: 'metricsLowDiskProtection',
    default: true,
    touchpoints: ['server/src/jobs/metricsRetention.ts', 'server/src/jobs/runMetricsRetention.ts',
      'server/src/db/vitalsSummary.ts', 'server/src/db/sleepStageSummary.ts', 'server/prisma/schema.prisma',
      'app/src/pages/SettingsPage/FeaturesSection/FeaturesSection.tsx'],
    depends_on: [],
    reversible: false,
    tests: ['server/src/jobs/metricsRetention.test.ts', 'server/src/jobs/runMetricsRetention.test.ts',
      'server/src/routes/metrics/vitals.test.ts', 'server/src/routes/metrics/sleepScore.test.ts',
      'app/src/pages/DataPage/SleepPage/SleepPage.vitals2.test.tsx'],
    upstream_offer: true,
    rationale: 'Preserves summaries before pruning their detail. Deleted detail cannot be restored.',
  },
  {
    id: 'raw-record-recovery',
    title: 'Recover after a corrupt RAW record',
    description: 'The live RAW reader scans for a complete later record after a decode failure '
      + 'and logs skipped bytes. A partial live tail is retried at the same offset.',
    category: 'biometrics',
    version: '3.7.0',
    flag: null,
    default: true,
    touchpoints: ['biometrics/stream/stream.py', 'biometrics/load_raw_files.py'],
    depends_on: ['biometrics'],
    reversible: true,
    tests: ['biometrics/__tests__/test_stream_helpers.py', 'biometrics/__tests__/test_raw_record_parser.py'],
    upstream_offer: true,
    rationale: 'Bug fix: one corrupt record must not stall the stream until file rotation.',
  },
  {
    id: 'integration-api-contract',
    title: 'Integration API contracts',
    description: 'Community client contracts, shared status polling and a bounded default sleep history.',
    category: 'platform',
    version: '3.7.0',
    flag: null,
    default: true,
    touchpoints: [
      'docs/INTEGRATIONS.md', 'server/src/routes/serverStatus/serverStatus.ts', 'server/src/serverStatus.ts',
      'server/src/db/services.ts', 'server/src/routes/metrics/sleep.ts',
      'app/src/pages/DataPage/SleepPage/SleepPage.tsx', 'app/src/pages/DataPage/SleepPage/SleepSideControl.tsx',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/routes/integrationsContract.test.ts', 'server/src/routes/serverStatus/serverStatus.test.ts',
      'server/src/serverStatusServices.test.ts', 'server/src/routes/metrics/rowsRange.test.ts',
      'app/src/pages/DataPage/SleepPage/SleepPage.selection.test.tsx',
    ],
    upstream_offer: true,
    rationale: 'Always on: bounds and shared reads reduce polling work; explicit history ranges remain available.',
  },
  {
    id: 'legacy-alarm-updates',
    title: 'Preserve later alarms on legacy writes',
    description: 'A single alarm write edits the first weekly alarm without discarding later alarms.',
    category: 'platform',
    version: '3.7.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/routes/schedules/schedules.ts', 'docs/INTEGRATIONS.md'],
    depends_on: ['agent'],
    reversible: true,
    tests: ['server/src/routes/schedules/schedulesValidation.test.ts'],
    upstream_offer: true,
    rationale: 'Always on: preventing loss of stored alarms is a bug fix and adds no stored fields.',
  },
  {
    id: 'side-alarm-dismissal',
    title: 'Dismiss only the ringing side',
    description: 'An idle dismiss sends no vibration command. A ringing side gets a one-second replacement '
      + 'without an unscoped alarm clear.',
    category: 'safety',
    version: '3.7.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/8sleep/dismissAlarm.ts'],
    depends_on: [],
    reversible: true,
    tests: ['server/src/8sleep/alarmDismiss.test.ts'],
    upstream_offer: true,
    rationale: 'Always on: a dismissal should leave the other sleeper\'s alarm untouched.',
  },
  {
    id: 'alarm-cover-pattern',
    title: 'Alarm pattern for mixed hardware',
    description: 'Builds up requires both a Pod 5 hub and cover. Other or unknown combinations use Double pulse.',
    category: 'safety',
    version: '3.7.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/jobs/alarmPattern.ts', 'server/src/jobs/alarmScheduler.ts', 'app/src/api/alarmPattern.ts'],
    depends_on: [],
    reversible: true,
    tests: ['server/src/jobs/alarmPattern.test.ts', 'app/src/pages/SchedulePage/SchedulePage.test.tsx'],
    upstream_offer: true,
    rationale: 'Always on: an unsupported vibration pattern may leave an alarm silent.',
  },
  {
    id: 'scheduler-confirmation',
    title: 'Clock and daily prime confirmation',
    description: 'Jobs arm when the system year is plausible. '
      + 'System status warns when the clock is not synchronized with NTP or sync status is unavailable. '
      + 'Daily priming reports failure if the Pod does not confirm it. Alarm dismissal dialogs track each side separately.',
    category: 'safety',
    version: '3.7.0',
    flag: null,
    default: true,
    touchpoints: [
      'server/src/jobs/clockSynchronization.ts', 'server/src/jobs/jobScheduler.ts', 'server/src/jobs/primeScheduler.ts',
      'server/src/serverStatus.ts', 'app/src/pages/StatusPage/StatusPage.tsx',
      'app/src/pages/ControlTempPage/AlarmDismissal.tsx',
    ],
    depends_on: [],
    reversible: true,
    tests: [
      'server/src/jobs/clockSynchronization.test.ts', 'server/src/jobs/jobSchedulerNtp.test.ts',
      'server/src/jobs/primeScheduler.test.ts', 'app/src/pages/ControlTempPage/AlarmDismissal.repeatAlarm.test.tsx',
      'app/src/pages/StatusPage/StatusPage.test.tsx',
    ],
    upstream_offer: true,
    rationale: 'Always on: schedules need a usable clock and maintenance failures need to be visible.',
  },
  {
    id: 'agent',
    title: 'Updates and rollback',
    description: 'In-app updates, rollback, switching to upstream free-sleep, and the Settings > Software page. '
      + 'Install and reset share the operation lock with updates, rollbacks and switches; install holds it '
      + 'through its health check and any restore. A systemd tmpfiles rule provisions the lock after boot.',
    category: 'platform',
    version: '3.6.0',
    flag: null,
    default: true,
    touchpoints: [
      'scripts/update.sh', 'scripts/rollback_pod.sh', 'scripts/switch-to-upstream.sh', 'scripts/install.sh',
      'scripts/reset.sh', 'scripts/setup_services.sh', 'server/src/jobs/operationLock.ts',
      'app/src/pages/SettingsPage/VersionsPage',
    ],
    depends_on: [],
    reversible: false,
    tests: [
      'server/src/updaterScripts.test.ts', 'server/src/rollbackScript.test.ts', 'server/src/installScript.test.ts',
      'server/src/resetScript.test.ts', 'server/src/operationSafety.test.ts', 'server/src/setupServicesScript.test.ts',
      'scripts/tests/test_operation_portability.py',
    ],
    upstream_offer: false,
    rationale: 'Always on, not individually removable: it is what makes everything else installable and reversible.',
  },
  {
    id: 'update-recovery',
    title: 'Recover an interrupted update at boot',
    description: 'An update marks its swap before moving the live tree. A timer starts one recovery attempt '
      + '45 seconds after boot when the marker remains: keep a healthy live install or try to restore the previous tree. '
      + 'The marker clears only after a health check passes. A timeout or failed restore keeps it for manual '
      + 'recovery. Database and settings backups are not restored. Checked on one Pod 5 with no marker, a hand-set '
      + 'marker and a power cut after the server stopped, before the tree move. A cut during the move is covered '
      + 'only by automated tests. Boot recovery records the outcome of an interrupted update, including server or '
      + 'Biometrics restart failures, so Settings shows the recovery result.',
    category: 'safety',
    version: '3.6.0',
    flag: null,
    default: true,
    touchpoints: [
      'scripts/update.sh', 'scripts/recover_update.sh', 'scripts/restore_helpers.sh', 'scripts/setup_services.sh',
      'scripts/systemd/free-sleep-recover-update.service', 'scripts/systemd/free-sleep-recover-update.timer',
      'scripts/rollback_pod.sh', 'scripts/switch-to-upstream.sh',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/updateRecoveryScript.test.ts', 'server/src/setupServicesScript.test.ts',
      'server/src/updaterBehavior.test.ts', 'server/src/updateResult.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Always on: a power loss cannot run the updater exit trap, so a marked swap needs a recovery '
      + 'attempt at boot. It acts only with a swap marker. Switching to upstream removes the recovery units '
      + 'and helpers after any pending recovery is settled.',
  },
  {
    id: 'no-telemetry',
    title: 'No telemetry',
    description: 'Sentry removed entirely from server, app, and python. No error-reporting dependency anywhere in the tree.',
    category: 'platform',
    version: '3.0.0',
    flag: null,
    default: true,
    touchpoints: [],
    depends_on: ['agent'],
    reversible: false,
    tests: [],
    upstream_offer: true,
    rationale: 'An absence, not a code path: baseline, nothing to gate, nothing to toggle.',
  },
  {
    id: 'security-hardening',
    title: 'Security hardening',
    description: 'CORS scoped to the LAN subnet, execute-route numeric argument bounds.',
    category: 'safety',
    version: '3.0.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/setup/middleware.ts', 'server/src/routes/execute/executeHelpers.ts'],
    depends_on: ['agent'],
    reversible: false,
    tests: [],
    upstream_offer: true,
    rationale: 'A correctness and safety fix, not a preference. Turning it off would just be shipping a known gap.',
  },
  {
    id: 'franken-hardening',
    title: 'Franken hardening',
    description: 'Per-command timeouts on the Franken socket, the /metrics/server endpoint, connection monitoring.',
    category: 'platform',
    version: '3.0.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/8sleep/frankenServer.ts', 'server/src/routes/metricsServer'],
    depends_on: ['agent'],
    reversible: false,
    tests: [],
    upstream_offer: false,
    rationale: 'Infrastructure hardening against a wedged hardware socket. Baseline for the same reason as security-hardening.',
  },
  {
    id: 'websocket-live-updates',
    title: 'Real-time WebSocket updates',
    description: 'Push device-status, service-health, and job events over /ws/events instead of only polling.',
    category: 'platform',
    version: '3.0.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/ws/wsServer.ts', 'app/src/api/eventStream.ts'],
    depends_on: ['agent'],
    reversible: true,
    tests: ['server/src/ws/wsServer.test.ts'],
    upstream_offer: false,
    rationale: 'Considered a real flag (features.ws), then reclassified baseline: a user gains '
      + 'nothing from turning off real-time updates, since the automatic polling fallback '
      + 'already covers any disconnection, and it is not restart-hot-swappable the way the '
      + 'other flags are.',
  },
  {
    id: 'biometrics',
    title: 'Biometrics',
    description: 'Heart rate, HRV, breathing rate, and presence detection from the piezo stream. At startup '
      + 'and after the setting is saved, reconcile the stream service with the Biometrics switch: enable '
      + 'and start when on, stop and disable when off. Retry while another operation or update recovery is pending.',
    category: 'biometrics',
    version: '3.6.0',
    flag: 'services.biometrics.enabled',
    default: false,
    touchpoints: [
      'server/src/db/servicesSchema.ts', 'server/src/jobs/biometrics.ts', 'server/src/routes/services/services.ts',
      'server/src/jobs/biometricsSync.ts', 'server/src/jobs/operationLock.ts', 'server/src/server.ts',
      'scripts/setup_services.sh', 'app/src/pages/SettingsPage/FeaturesSection',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/db/services.test.ts', 'server/src/jobs/biometrics.test.ts', 'server/src/jobs/privilegedJobs.test.ts',
      'server/src/jobs/biometricsSwitchOrder.test.ts', 'server/src/jobs/biometricsReconcile.test.ts',
      'server/src/jobs/biometricsSync.test.ts',
      'server/src/routes/services/servicesBiometricsSwitch.test.ts', 'server/src/setupServicesScript.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Real, existing, user-facing toggle, but with install-precondition and '
      + 'systemd start and stop side effects a plain settings.features boolean does not fit, so it '
      + 'stays in its own store rather than joining FeaturesSchema. One coarse feature, not '
      + 'many: the presence-accuracy fixes within it are baseline correctness, not '
      + 'separately toggleable.',
  },
  {
    id: 'sleep-stages-score',
    title: 'Sleep score',
    description: 'The sleep score API. Not shown in the app.',
    category: 'biometrics',
    version: '3.0.1',
    flag: 'sleepScore',
    default: true,
    touchpoints: [
      'server/src/routes/metrics/sleepScore.ts', 'server/src/routes/metrics/sleepStages.ts',
      'app/src/components/SleepFitnessCard.tsx',
    ],
    depends_on: ['biometrics'],
    reversible: true,
    tests: ['server/src/routes/metrics/sleepScoreGuard.test.ts'],
    upstream_offer: false,
    rationale: 'Before 3.1.0, neither route required biometrics to be enabled, so both could '
      + 'report a result without data. They now require biometrics and sufficient measurements.',
  },
  {
    id: 'honest-status',
    title: 'Clear status',
    description: 'Status page shows waiting_for_data and calibration-skip as calm states, not failures; false-alarm fixes.',
    category: 'safety',
    version: '3.0.0',
    flag: null,
    default: true,
    touchpoints: ['app/src/pages/StatusPage'],
    depends_on: ['agent'],
    reversible: false,
    tests: [],
    upstream_offer: false,
    rationale: 'Baseline, always on, but shows less when biometrics is off: some rows only mean anything with real biometrics data behind them.',
  },
  {
    id: 'level-temperature-display',
    title: 'Level temperature display',
    description: 'The -10 to +10 level option in the temperature format picker.',
    category: 'ui',
    version: '3.0.1',
    flag: 'levelTemps',
    default: true,
    touchpoints: [
      'app/src/pages/SettingsPage/DeviceSettingsSection/TemperatureFormatSelector.tsx',
      'server/src/routes/settings/settingsGuards.ts',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: ['server/src/routes/settings/settingsGuards.test.ts'],
    upstream_offer: false,
    rationale: 'Real toggle, not just a display preference: the temperatureFormat setting '
      + 'already existed, this gates whether level is offered as a legal choice at all, '
      + 'with a server precondition against disabling it while a pod is actively using it.',
  },
  {
    id: 'one-off-alarms',
    title: 'One-off alarms',
    description: 'Single-fire alarms, separate from the recurring per-day alarm.',
    category: 'ui',
    version: '3.0.1',
    flag: 'oneOffAlarms',
    default: true,
    touchpoints: ['app/src/pages/SchedulePage/OneOffAlarmSection.tsx', 'server/src/jobs/jobScheduler.ts', 'server/src/jobs/alarmScheduler.ts'],
    depends_on: ['agent'],
    reversible: true,
    tests: [],
    upstream_offer: false,
    rationale: 'Turning it off hides the section and stops scheduling new checks; a '
      + 'previously-armed alarm\'s stored data is untouched, so re-enabling re-arms it '
      + 'without any migration.',
  },
  {
    id: 'design-system',
    title: 'Design system',
    description: 'Three themes, chosen per device in Settings > Bed and sides: lamp (the default), free-sleep classic and jmew. '
      + 'One token set per theme for colour, type voice and '
      + 'corners, a temperature scale per theme with a neutral zero, and the same layout and 44 px targets in each.',
    category: 'ui',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: ['app/src/theme.ts', 'app/src/design/tokens.ts', 'app/src/design/themes', 'app/src/design/themePreference.ts',
      'app/src/design/themeBoot.ts', 'app/src/pages/SettingsPage/ThemePicker.tsx'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/design/themes/themes.test.ts', 'app/src/design/themePreference.test.ts',
      'app/src/pages/SettingsPage/ThemePicker.test.tsx'],
    upstream_offer: false,
    rationale: 'Always on: a look is a per device preference kept in the browser, not a server setting, so older versions '
      + 'ignore it and going back needs no migration. The features.nightstandTheme key from 3.1.0 is still not read; it stays '
      + 'in the schema so stored settings keep validating.',
  },
  {
    id: 'logs-viewer',
    title: 'Logs viewer',
    description: 'The Logs page and its live-tail API.',
    category: 'platform',
    version: '3.0.1',
    flag: null,
    default: 'n/a',
    touchpoints: ['app/src/pages/DataPage/LogsPage/LogsPage.tsx', 'server/src/routes/logs/logs.ts'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['server/src/routes/logs/logsHelpers.test.ts'],
    upstream_offer: false,
    rationale: 'Baseline, not a toggle. This shipped as a flag that also had the log API '
      + 'refuse a direct request, on the reasoning that an operator might want logs '
      + 'unreadable. That reasoning does not hold here: there is one operator, who is '
      + 'the owner, and logs are how this pod gets diagnosed when something breaks. A '
      + 'switch whose only effect is to hide the evidence from the person debugging is '
      + 'not a feature. Retired 2026-07-16.',
  },
  {
    id: 'base-control',
    title: 'Adjustable base control',
    description: 'BLE control for an adjustable base, auto-hides when none is configured.',
    category: 'platform',
    version: '3.0.0',
    flag: 'auto: /persistent/AdjustableBaseConfiguration.json presence',
    default: 'n/a',
    touchpoints: ['server/src/8sleep/trimixBaseControl.ts', 'app/src/components/Navbar.tsx'],
    depends_on: ['agent'],
    reversible: true,
    tests: [],
    upstream_offer: false,
    rationale: 'Auto-gated by hardware presence, not a user-settable flag. Low priority: '
      + 'hardware not present on this pod, first candidate to drop if it stops being a clean '
      + 'dormant feature.',
  },
  {
    id: 'presence-auto-off',
    title: 'Presence auto-off',
    description: 'Turns a side off after 45 minutes with no one on it, outside its scheduled on-window.',
    category: 'biometrics',
    version: '3.4.0',
    flag: 'presenceAutoOff',
    default: true,
    touchpoints: ['server/src/8sleep/presenceAutoOffMonitor.ts', 'app/src/pages/SettingsPage/FeaturesSection'],
    depends_on: ['biometrics'],
    reversible: true,
    tests: ['server/src/8sleep/presenceAutoOffMonitor.test.ts'],
    upstream_offer: false,
    rationale: 'On by default so existing pods behave as before. Needs presence from '
      + 'biometrics and holds whenever presence is unknown, so it never acts without it. '
      + 'Off keeps tracking state, so turning it back on mid-session measures idle time '
      + 'correctly.',
  },
  {
    id: 'cover-buttons',
    title: 'Cover buttons',
    description: 'For a Pod 4 hub with a Pod 5 cover, whose firmware ignores short clicks on the cover\'s '
      + 'plus and minus buttons. Reads those clicks from RAW files and steps that side by 1 F per click, '
      + '15 to 25 s later, because the firmware writes its log in batches. A Pod 5 hub handles its buttons '
      + 'itself, so this does nothing there.',
    category: 'platform',
    version: '3.7.0',
    flag: 'coverButtons',
    default: false,
    touchpoints: [
      'server/src/8sleep/buttonMonitor.ts', 'server/src/8sleep/buttonEvents.ts',
      'app/src/pages/SettingsPage/FeaturesSection',
    ],
    depends_on: [],
    reversible: true,
    tests: [
      'server/src/8sleep/buttonMonitor.test.ts', 'server/src/8sleep/buttonEvents.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Off by default, for a Pod 4 hub with a Pod 5 cover that ignores short plus and minus clicks. '
      + 'Reads no RAW files while off. Each ignored click steps that side by 1 F, with a 15 to 25 s delay '
      + 'because the firmware writes its log in batches. A Pod 5 hub handles its buttons itself, so this does nothing there.',
  },
  {
    id: 'biometrics-v2',
    title: 'New sleep tracking (beta)',
    description: 'Tells the two sides apart with the bed\'s capacitance sensors, in live presence and the '
      + 'nightly analysis, keeps vitals through short trips out of bed, and estimates heart rate and '
      + 'breathing with methods built for the bed\'s vibration sensors.',
    category: 'biometrics',
    version: '3.5.0',
    flag: 'biometricsV2',
    default: false,
    touchpoints: [
      'biometrics/presence', 'biometrics/features.py', 'biometrics/stream/stream.py',
      'biometrics/stream/stream_processor.py', 'biometrics/stream/biometric_processor.py',
      'biometrics/sleep_detection/sleep_detector.py', 'biometrics/sleep_detection/cap_data.py',
      'biometrics/sleep_detection/calibrate_sensor_thresholds.py', 'biometrics/load_raw_files.py',
      'biometrics/calibration.py', 'server/src/db/settingsSchema.ts', 'server/src/features/biometricsV2.ts',
      'app/src/pages/SettingsPage/FeaturesSection', 'app/src/pages/SettingsPage/SettingsPage.tsx',
      'server/src/features/sleepTrackingValidation.ts', 'server/src/routes/calibration',
      'app/src/api/sleepTrackingValidation.ts',
      'biometrics/vitals2', 'biometrics/stream/vitals2_stream.py', 'biometrics/stream/pump_speed.py',
      'biometrics/db.py',
      'server/src/routes/metrics/vitalsV2.ts', 'server/src/routes/metrics/vitals.ts',
      'server/src/db/vitalsRecordSchema.ts', 'app/src/pages/DataPage/SleepPage/SleepPage.tsx',
    ],
    depends_on: ['biometrics'],
    reversible: true,
    tests: [
      'biometrics/__tests__/test_features.py', 'biometrics/__tests__/test_presence_cap.py',
      'biometrics/__tests__/test_presence_detector.py', 'biometrics/__tests__/test_presence_params.py',
      'biometrics/__tests__/test_presence_calibration.py', 'biometrics/__tests__/test_presence_loader.py',
      'biometrics/__tests__/test_presence_replay.py', 'biometrics/__tests__/test_sleep_detector_presence.py',
      'biometrics/__tests__/test_stream_presence.py', 'biometrics/__tests__/test_vitals_state_retention.py',
      'biometrics/__tests__/test_toggle_off_identity.py', 'server/src/features/biometricsV2.test.ts',
      'app/src/pages/SettingsPage/FeaturesSection/FeaturesSection.test.tsx',
      'app/src/pages/SettingsPage/FeaturesSection/FeaturesSection.partialPayload.test.tsx',
      'app/src/pages/SettingsPage/SettingsPage.categories.test.tsx',
      'biometrics/__tests__/test_presence_sensors.py', 'biometrics/__tests__/test_presence_piezo.py',
      'biometrics/__tests__/test_presence_guard.py', 'biometrics/__tests__/test_legacy_capacitance.py',
      'biometrics/__tests__/test_presence_v2_identity.py', 'biometrics/__tests__/test_presence_model.py',
      'server/src/features/sleepTrackingValidation.test.ts',
      'server/src/routes/calibration/calibrationView.test.ts',
      'biometrics/__tests__/test_stream_vitals2.py', 'biometrics/__tests__/test_stream_vitals_legacy_output.py',
      'biometrics/__tests__/test_vitals2_hr.py', 'biometrics/__tests__/test_vitals2_attribution.py',
      'biometrics/__tests__/test_vitals2_hrv.py', 'biometrics/__tests__/test_vitals2_resp.py',
      'biometrics/__tests__/test_vitals2_lazy_import.py', 'server/src/routes/metrics/vitals.test.ts',
      'app/src/pages/DataPage/SleepPage/SleepPage.vitals2.test.tsx',
    ],
    upstream_offer: false,
    rationale: 'Off by default while it is checked against more nights and more beds. Off leaves live '
      + 'presence, the nightly analysis and every stored value exactly as before. Older versions keep '
      + 'the setting and ignore it. On a Pod it was not checked on, the app marks it as experimental.',
  },
  {
    id: 'daily-reboot',
    title: 'Daily reboot',
    description: 'Restarts the pod an hour before daily priming.',
    category: 'platform',
    version: '3.4.0',
    flag: 'settings.rebootDaily',
    default: true,
    touchpoints: ['server/src/jobs/primeScheduler.ts', 'app/src/pages/SettingsPage/DailyPriming.tsx'],
    depends_on: ['agent'],
    reversible: true,
    tests: [],
    upstream_offer: false,
    rationale: 'A setting since upstream 2.x with no control in the app until 3.4.0. It is '
      + 'scheduled with daily priming, so it only runs while priming is on, and the control '
      + 'sits with priming for that reason.',
  },
  {
    id: 'raw-archive-retention',
    title: 'RAW archive retention',
    description: 'Keeps overnight sensor files past the firmware\'s rolling buffer for a set number of days.',
    category: 'biometrics',
    version: '3.3.0',
    flag: 'settings.rawArchiveRetentionDays',
    default: 'n/a',
    touchpoints: [
      'scripts/archive-raw.sh', 'server/src/jobs/rawArchiveConf.ts',
      'app/src/pages/SettingsPage/DeviceSettingsSection/RawArchiveRetention.tsx',
    ],
    depends_on: ['biometrics'],
    reversible: true,
    tests: [],
    upstream_offer: false,
    rationale: 'A number of days rather than on or off. Without the archive the daily sleep '
      + 'analysis sees only the last ~75 minutes of data, so it is not offered as a switch.',
  },
  {
    id: 'water-tank-status',
    title: 'Water tank status',
    description: 'A Status page entry for the water tank level, with its last change recorded.',
    category: 'ui',
    version: '3.3.0',
    flag: null,
    default: true,
    touchpoints: ['server/src/8sleep/waterLevelTracker.ts', 'app/src/pages/StatusPage/statusMeta.ts'],
    depends_on: ['agent'],
    reversible: false,
    tests: [],
    upstream_offer: false,
    rationale: 'Always on: a read-only status row with nothing to turn off.',
  },
  {
    id: 'service-memory-limits',
    title: 'Service memory limits',
    description: 'Memory caps for the Nightstand services so a runaway job cannot take memory from the pod\'s firmware.',
    category: 'safety',
    version: '3.3.0',
    flag: null,
    default: true,
    touchpoints: ['scripts/setup_resource_limits.sh'],
    depends_on: ['agent'],
    reversible: true,
    tests: ['server/src/resourceLimitsScript.test.ts'],
    upstream_offer: false,
    rationale: 'Always on, as a safety measure. Switching to upstream free-sleep removes the limits.',
  },
  {
    id: 'health-restart',
    title: 'Restart a server that stops answering',
    description: 'A one-minute timer restarts the server after three failed status checks in a row, '
      + 'except while an install, reset, update, rollback or switch holds the operation lock or the server has just started.',
    category: 'safety',
    version: '3.6.0',
    flag: null,
    default: true,
    touchpoints: [
      'scripts/health_check.sh', 'scripts/systemd/free-sleep-health.service', 'scripts/systemd/free-sleep-health.timer',
      'scripts/setup_services.sh', 'scripts/switch-to-upstream.sh',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: ['server/src/healthCheckScript.test.ts', 'server/src/setupServicesScript.test.ts'],
    upstream_offer: false,
    rationale: 'Safety: restarts a server that stops answering, since schedules and alarms run in it. '
      + 'Switching to upstream free-sleep removes the timer; an older release leaves it installed as a no-op.',
  },
  {
    id: 'snapshot-pruning',
    title: 'Prune old database snapshots',
    description: 'Updates, switches, installs and database resets keep the newest three database snapshots and any '
      + 'from the last week, then remove more, oldest first, only while free space on /persistent is under 512 MB. '
      + 'Only files named like Nightstand\'s own snapshots are ever removed.',
    category: 'safety',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: [
      'scripts/prune_db_snapshots.sh', 'scripts/update.sh', 'scripts/switch-to-upstream.sh', 'scripts/install.sh',
      'scripts/reset_db.sh',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: ['server/src/pruneSnapshotsScript.test.ts'],
    upstream_offer: false,
    rationale: 'Safety: every update, switch, install and reset adds a full database copy, and /persistent also holds '
      + 'firmware data and Wi-Fi settings. Always on, since the space floor is what protects the Pod. Older releases '
      + 'and upstream free-sleep do not prune; migration snapshots are never removed.',
  },
  {
    id: 'hardware-watchdog',
    title: 'Hardware watchdog',
    description: 'After a successful install or update, sets systemd\'s RuntimeWatchdogSec to 30 seconds through a drop-in, '
      + 'after a one-minute trial from /run, so a frozen kernel or PID 1 resets the Pod. Pod 5 only (mtk-wdt, 31 s '
      + 'maximum, hub revision G53 or later); skipped where the device, systemd or the driver\'s timeout limits cannot '
      + 'hold it, after a trial that did not finish, and after the owner turned it off with --remove.',
    category: 'safety',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: [
      'scripts/setup_watchdog.sh', 'scripts/update.sh', 'scripts/install.sh', 'scripts/migrate/pod-installer.sh',
      'scripts/switch-to-upstream.sh', 'scripts/rollback_pod.sh', 'scripts/reset.sh',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/watchdogScript.test.ts', 'server/src/updaterScripts.test.ts', 'server/src/migrationScripts.test.ts',
      'server/src/rollbackScript.test.ts', 'server/src/switchToUpstreamScript.test.ts', 'server/src/resetScript.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Safety: a frozen system otherwise leaves the Pod with no server and no cooling until it is unplugged. '
      + 'Switching to upstream free-sleep removes the drop-in; it never overrides a watchdog set up some other way.',
  },
  {
    id: 'network-watchdog',
    title: 'Restart the Pod when its Wi-Fi driver has died',
    description: 'Where the stock Wi-Fi driver is loaded and the hardware watchdog is on, a one-minute timer restarts '
      + 'the Pod when the gateway has not answered for 5 minutes after a crash of that driver, or for 20 minutes '
      + 'while its scans fail with the error the crashed driver gives. A router that is away while scans work never '
      + 'counts. Not in the first 10 minutes after boot or while an update, rollback, switch, install, reset or '
      + 'biometrics install runs; at most once in 6 hours and 3 times in 24.',
    category: 'safety',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: [
      'scripts/network_watchdog.sh', 'scripts/systemd/free-sleep-network-watchdog.service',
      'scripts/systemd/free-sleep-network-watchdog.timer', 'scripts/setup_services.sh', 'scripts/rollback_pod.sh',
      'scripts/switch-to-upstream.sh', 'scripts/migrate/restore-original-fork.sh',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/networkWatchdogScript.test.ts', 'server/src/setupServicesScript.test.ts',
      'server/src/rollbackScript.test.ts', 'server/src/switchToUpstreamScript.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Safety: when the driver dies the Pod keeps running but cannot be reached, and unplugging it has '
      + 'been the only known fix; whether a restart brings Wi-Fi back is not yet confirmed. A restart after this '
      + 'crash can hang, so it waits unless the hardware watchdog can reset a hung shutdown. Always on, '
      + 'since the evidence rules and rate limits keep it from restarting for an ordinary outage. Switching to '
      + 'upstream free-sleep removes the timer; an older release leaves it installed as a no-op.',
  },

  {
    id: 'primary-navigation',
    title: 'Named primary navigation',
    description: 'Bed, Schedule, Sleep and Settings links follow the current page and support browser history.',
    category: 'ui',
    version: '3.4.0',
    flag: null,
    default: true,
    touchpoints: ['app/src/components/Navbar.tsx', 'app/src/AppRoutes.tsx'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/components/Navbar.test.tsx', 'app/e2e/navigation.spec.ts'],
    upstream_offer: false,
    rationale: 'Navigation is required to reach the application pages.',
  },
  {
    id: 'system-status-summary',
    title: 'Service status summary',
    description: 'System groups service states and shows errors before healthy details.',
    category: 'ui',
    version: '3.4.0',
    flag: null,
    default: true,
    touchpoints: ['app/src/pages/StatusPage'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/pages/StatusPage/StatusPage.test.tsx'],
    upstream_offer: false,
    rationale: 'Service errors must remain visible without an optional display setting.',
  },
  {
    id: 'log-connection-status',
    title: 'Log connection status',
    description: 'Logs show live, paused and disconnected states and replace replayed tails on reconnect.',
    category: 'ui',
    version: '3.4.0',
    flag: null,
    default: true,
    touchpoints: ['app/src/pages/DataPage/LogsPage'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/pages/DataPage/LogsPage/LogsPage.connection.test.tsx'],
    upstream_offer: false,
    rationale: 'Connection state is needed to interpret the displayed log lines.',
  },
  {
    id: 'calibration-confirmation',
    title: 'Manual calibration confirmation',
    description: 'Manual presence calibration asks the user to leave the selected side empty.',
    category: 'ui',
    version: '3.4.0',
    flag: null,
    default: true,
    touchpoints: ['app/src/pages/StatusPage/StatusRow.tsx'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/pages/StatusPage/StatusRow.test.tsx'],
    upstream_offer: false,
    rationale: 'The occupancy precondition applies whenever manual calibration is requested.',
  },
  {
    id: 'bed-side-tiles',
    title: 'Named bed controls',
    description: 'Named side tiles, read-only temperature gauge and large stepper controls.',
    category: 'ui',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: ['app/src/components/SideControl.tsx', 'app/src/pages/ControlTempPage'],
    depends_on: ['agent'],
    reversible: false,
    tests: [
      'app/src/components/SideControl.test.tsx', 'app/src/lib/temperatureColor.test.ts',
      'app/src/pages/ControlTempPage/TemperatureDial.test.tsx', 'app/src/pages/ControlTempPage/TemperatureButtons.queue.test.tsx',
    ],
    upstream_offer: false,
    rationale: 'Side identity and readable controls are required for operating the bed.',
  },
  {
    id: 'grouped-night-schedule',
    title: 'Grouped night schedule',
    description: 'Bedtime, overnight and wake controls with relative power off over existing schedule times.',
    category: 'ui',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: ['app/src/pages/SchedulePage'],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/pages/SchedulePage/ScheduleTimeline.routine.test.tsx'],
    upstream_offer: false,
    rationale: 'Grouping and time labels describe the stored schedule without adding a separate behavior to disable.',
  },
  {
    id: 'sleep-night-summary',
    title: 'Recorded night summary',
    description: 'The latest recorded night, time in bed, trips out of bed and explicit missing-data states.',
    category: 'ui',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: ['app/src/pages/DataPage/SleepPage', 'app/src/components/SleepFitnessCard.tsx'],
    depends_on: ['agent'],
    reversible: false,
    tests: [
      'app/src/pages/DataPage/SleepPage/SleepPage.selection.test.tsx',
      'app/src/pages/DataPage/SleepPage/SleepPage.missing.test.tsx',
      'app/src/components/SleepFitnessCard.test.tsx',
    ],
    upstream_offer: false,
    rationale: 'The summary presents existing sleep data; Biometrics controls whether that data is recorded.',
  },
  {
    id: 'settings-groups',
    title: 'Grouped settings',
    description: 'Bed and sides, Features, Software, and Pod and diagnostics with shared subpage navigation.',
    category: 'ui',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: [
      'app/src/pages/SettingsPage', 'app/src/pages/DataPage/Header.tsx',
      'app/src/pages/SettingsPage/VersionsPage', 'app/src/pages/StatusPage', 'app/src/state/updateAttentionStore.ts',
    ],
    depends_on: ['agent'],
    reversible: false,
    tests: ['app/src/AppRoutes.test.tsx', 'app/src/pages/SettingsPage/SettingsPage.categories.test.tsx'],
    upstream_offer: false,
    rationale: 'Settings navigation is required to reach the existing controls.',
  },
  {
    id: 'schedule-pause',
    title: 'Pause schedule',
    description: 'Pause one side\'s schedule for tonight, until a set time or until resumed. '
      + 'An off side turns on when the pause ends if its night is in progress. The saved schedule and the one-time alarm are kept.',
    category: 'platform',
    version: '3.6.0',
    flag: null,
    default: true,
    touchpoints: [
      'server/src/jobs/schedulePause.ts', 'server/src/jobs/pauseResume.ts', 'server/src/jobs/resumeSchedule.ts',
      'server/src/jobs/powerScheduler.ts',
      'server/src/jobs/temperatureScheduler.ts', 'server/src/jobs/alarmScheduler.ts', 'server/src/jobs/jobScheduler.ts',
      'server/src/8sleep/presenceAutoOffMonitor.ts', 'server/src/routes/settings/settingsGuards.ts',
      'app/src/pages/ControlTempPage/PauseScheduleSheet.tsx', 'app/src/pages/ControlTempPage/SchedulePauseNotice.tsx',
      'app/src/pages/ControlTempPage/UpcomingNight.tsx', 'app/src/components/SideControl.tsx',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/jobs/schedulePause.test.ts', 'server/src/jobs/schedulePauseJobs.test.ts',
      'server/src/jobs/schedulePauseAlarms.test.ts', 'server/src/jobs/pauseResume.test.ts', 'server/src/jobs/pauseResumeSchedule.test.ts',
      'server/src/jobs/jobSchedulerPause.test.ts', 'server/src/routes/settings/settingsGuards.test.ts',
      'app/src/pages/ControlTempPage/PauseScheduleSheet.test.tsx', 'app/src/pages/ControlTempPage/UpcomingNight.pause.test.tsx',
      'app/e2e/pause-schedule.spec.ts',
    ],
    upstream_offer: false,
    rationale: 'A user action with no background behavior change until someone pauses a side, so there is nothing to turn off. '
      + 'Older versions ignore the setting.',
  },
  {
    id: 'missed-alarm-report',
    title: 'Missed alarm report',
    description: 'Records alarms that could not ring: the server was not running, the Pod answered too late, '
      + 'the command failed or was not confirmed, this server hit an error, or the side was off.',
    category: 'safety',
    version: 'n/a',
    flag: null,
    default: true,
    touchpoints: [
      'server/src/jobs/alarmLedger.ts', 'server/src/jobs/alarmScheduler.ts', 'server/src/jobs/alarmActivity.ts',
      'server/src/jobs/jobScheduler.ts', 'server/src/jobs/alarmOverrideGate.ts', 'server/src/jobs/rhythms/scheduleRhythms.ts',
      'server/src/routes/alarm/missedAlarms.ts', 'server/src/setup/routes.ts',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/jobs/alarmLedger.test.ts', 'server/src/jobs/alarmLedgerOverride.test.ts',
      'server/src/routes/alarm/missedAlarms.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Safety: tells the user when an alarm could not ring. Always on, with nothing to turn off. '
      + 'It writes one extra file in the data folder, which older versions ignore.',
  },
  {
    id: 'rhythms',
    title: 'Rhythms',
    description: 'Named sleep plans per side, a weekly plan, date changes and an optional Smart Schedule temperature curve.',
    category: 'platform',
    version: '3.5.0',
    flag: 'rhythms',
    default: false,
    touchpoints: [
      'server/src/db/settingsSchema.ts', 'server/src/db/rhythmsSchema.ts', 'server/src/db/rhythms.ts', 'server/src/jobs/rhythms',
      'server/src/routes/rhythms/rhythms.ts', 'server/src/jobs/jobScheduler.ts', 'server/src/jobs/scheduleQueries.ts',
      'server/src/jobs/alarmActivity.ts', 'server/src/jobs/alarmScheduler.ts', 'server/src/jobs/powerScheduler.ts',
      'server/src/routes/deviceStatus/updateDeviceStatus.ts', 'server/src/routes/settings/settingsGuards.ts',
      'server/src/routes/update/update.ts', 'server/src/setup/routes.ts',
      'scripts/update.sh', 'scripts/rollback_pod.sh', 'scripts/switch-to-upstream.sh',
      'server/src/db/smartCurve.ts', 'server/src/8sleep/presenceStale.ts', 'server/src/8sleep/presenceAutoOffMonitor.ts',
      'server/src/jobs/scheduleOverride.ts', 'app/src/api/smartCurve.ts',
      'app/src/api/rhythms.ts', 'app/src/api/rhythmsResponse.ts', 'app/src/api/rhythmDays.ts', 'app/src/api/rhythmWake.ts',
      'app/src/api/api.ts', 'app/src/pages/SchedulePage/ScheduleTab.tsx', 'app/src/pages/SchedulePage/rhythms',
      'app/src/pages/ControlTempPage/useBedSleeps.ts', 'app/src/pages/ControlTempPage/sleepEvents.ts',
      'app/src/pages/ControlTempPage/smartPhase.ts', 'app/src/pages/SettingsPage/FeaturesSection/EnableRhythmsDialog.tsx',
      'app/src/pages/SettingsPage/FeaturesSection/DisableRhythmsDialog.tsx',
      'app/src/pages/SettingsPage/FeaturesSection/turnOffPreview.ts', 'app/src/pages/SettingsPage/VersionsPage/RhythmsLeaveNote.tsx',
      'app/src/mocks/rhythmsMock.ts',
      'server/src/db/smartOff.ts', 'server/src/jobs/rebootTime.ts', 'server/src/jobs/primeScheduler.ts', 'server/src/jobs/rebuildState.ts',
      'app/src/api/smartOff.ts', 'fixtures/compat/v3.5.0/rhythmsSchema.ts.txt',
      'app/src/pages/SchedulePage/ScheduleTimeline.tsx', 'app/src/pages/ControlTempPage/TemperatureLabel.tsx', 'app/src/mocks/handlers.ts',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/jobs/rhythms/equivalence.test.ts', 'server/src/db/rhythms.test.ts', 'server/src/routes/rhythms/rhythms.test.ts',
      'server/src/routes/rhythms/rhythmsSwitchRoutes.test.ts', 'server/src/routes/settings/settingsGuards.test.ts',
      'server/src/jobs/rhythms/scheduleRhythms.test.ts', 'server/src/jobs/rhythms/runEvent.test.ts',
      'server/src/jobs/rhythms/gates.test.ts', 'server/src/jobs/rhythms/handoff.test.ts',
      'server/src/jobs/rhythms/keptAlarms.test.ts', 'server/src/jobs/rhythms/lifecycle.test.ts',
      'server/src/jobs/rhythms/engineSwitch.test.ts', 'server/src/jobs/scheduleQueries.test.ts',
      'server/src/rhythmsFileSafety.test.ts', 'server/src/setup/leaveHookWiring.test.ts',
      'server/src/db/smartCurve.test.ts', 'server/src/jobs/rhythms/smartSleep.test.ts', 'server/src/jobs/rhythms/resolveSmart.test.ts',
      'server/src/jobs/rhythms/confirmation.test.ts', 'server/src/jobs/rhythms/curveController.test.ts',
      'server/src/jobs/rhythms/onsetEstimate.test.ts', 'server/src/jobs/rhythms/history.test.ts',
      'server/src/jobs/rhythms/curveRuntime.test.ts', 'server/src/jobs/rhythms/scheduleRhythmsSmart.test.ts',
      'server/src/routes/rhythms/rhythmsLive.test.ts', 'app/src/api/smartCurve.test.ts',
      'app/src/api/rhythms.test.tsx', 'app/src/pages/SchedulePage/rhythms/RhythmsPage.test.tsx',
      'app/src/pages/ControlTempPage/BedRhythms.test.tsx', 'app/src/pages/SettingsPage/FeaturesSection/turnOffPreview.test.ts',
      'server/src/db/rhythmsCompat.test.ts', 'server/src/db/smartOff.test.ts', 'server/src/jobs/rebootTime.test.ts',
      'server/src/jobs/rhythms/offWhenUp.test.ts', 'server/src/jobs/rhythms/resolveOff.test.ts', 'server/src/jobs/alarmActivity.test.ts',
      'server/src/jobs/rhythms/curveControllerOff.test.ts', 'server/src/jobs/rhythms/smartOffRuntime.test.ts',
      'app/src/pages/SchedulePage/ScheduleTimeline.getUp.test.tsx', 'app/src/api/rhythmsLiveOff.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Off by default. Its data lives only in rhythmsDB.json and it never writes schedulesDB.json, so turning it '
      + 'off, rolling back or switching to upstream leaves the weekly schedule exactly as it was.'
      + ' A rhythm set to turn off when the person gets up carries one optional key, which 3.5.0 drops on read.',
  },
  {
    id: 'tap-alarm',
    title: 'Alarm taps',
    description: 'Accepts the alarm tap action upstream uses, which has no effect yet. On a Pod 5 the firmware '
      + 'handles a double or triple tap during an alarm and does not pass it through the tap counters. '
      + 'A later dismissAlarm value above the highest seen for the same active alarm clears the side\'s ringing '
      + 'record and pending snooze without sending a command. Confirmed on one Pod 5: a double tap stopped '
      + 'the alarm in firmware, dismissAlarm rose, and Nightstand cleared its ringing state and logged the dismissal.',
    category: 'platform',
    version: '3.6.0',
    flag: null,
    default: true,
    touchpoints: [
      'server/src/8sleep/tapAlarm.ts', 'server/src/8sleep/frankenMonitor.ts', 'server/src/jobs/activeAlarms.ts',
      'server/src/jobs/alarmScheduler.ts', 'server/src/8sleep/firmwareAlarmDismiss.ts',
      'server/src/8sleep/loadDeviceStatus.ts', 'server/src/8sleep/frankenServer.ts',
    ],
    depends_on: ['agent'],
    reversible: true,
    tests: [
      'server/src/8sleep/tapAlarm.test.ts', 'server/src/8sleep/alarmDismiss.test.ts', 'server/src/8sleep/frankenMonitor.test.ts',
      'server/src/8sleep/firmwareAlarmDismiss.test.ts', 'server/src/8sleep/frankenAlarmDismiss.test.ts',
      'server/src/8sleep/loadDeviceStatus.test.ts',
    ],
    upstream_offer: false,
    rationale: 'Always on: accepts an existing tap setting and reads firmware dismissals so the server can '
      + 'clear a stale ringing record. A tap set to anything else behaves as before, and older versions keep the setting.',
  },
];
